version: '3.1'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    env_file: 
      - ./instance/production.env
    
  db:
    image: postgres
    restart: always
    env_file:
      - ./instance/production.env
      # POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      # POSTGRES_DB: postgres
      # POSTGRES_USER: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    env_file:
      - ./instance/production.env

  worker:
    build:
      context: .
    command: celery worker info -A app.celery_worker.celery -B -l 
    depends_on:
      - "redis"
    env_file:
      - ./instance/production.env
    