"""empty message

Revision ID: 065f3d0a3ec8
Revises: bed1d1a5877f
Create Date: 2020-03-15 17:03:20.868675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065f3d0a3ec8'
down_revision = 'bed1d1a5877f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_price_key', 'offer', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('offer_price_key', 'offer', ['price'])
    # ### end Alembic commands ###
